package com.fromzerotohero.mission.agent;

import com.fromzerotohero.mission.security.TenantContext;
import com.fromzerotohero.mission.workitem.Priority;
import com.fromzerotohero.mission.workitem.WorkItem;
import com.fromzerotohero.mission.workitem.WorkItemRepository;
import com.fromzerotohero.mission.workitem.WorkStatus;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.UUID;
import org.slf4j.MDC;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class AgentOrchestrator {
    private static final int REQUIRED_TOOL_CALLS = 3;
    private final WorkItemRepository workItems;
    private final AgentRunRepository runs;
    private final TenantContext tenantContext;
    private final GoalPlanner planner;
    private final AgentPolicyEngine policy;

    public AgentOrchestrator(WorkItemRepository workItems, AgentRunRepository runs,
            TenantContext tenantContext, GoalPlanner planner, AgentPolicyEngine policy) {
        this.workItems = workItems;
        this.runs = runs;
        this.tenantContext = tenantContext;
        this.planner = planner;
        this.policy = policy;
    }

    @Transactional
    public AgentResponse plan(AgentRequest request, String requestedKey) {
        UUID tenantId = tenantContext.tenantId();
        String idempotencyKey = normalizeKey(requestedKey);
        var existing = runs.findByTenantIdAndIdempotencyKey(tenantId, idempotencyKey);
        if (existing.isPresent()) return response(existing.get(), true);

        String goal = request.goal().trim().replaceAll("\\s+", " ");
        String normalized = goal.toLowerCase(Locale.ROOT);
        String classification = planner.classify(normalized);
        int budget = request.effectiveToolBudget();
        AgentPolicyEngine.Decision decision = policy.evaluate(normalized, request.createWorkItems(), budget);

        List<Long> ids = decision.outcome().equals("EXECUTED")
                ? createWorkItems(goal, classification, priority(normalized)) : List.of();
        AgentRun run = runs.save(new AgentRun(tenantId, tenantContext.userId(), correlationId(), goal,
                classification, decision.outcome(), ids.size(), idempotencyKey, budget, ids));
        return response(run, false);
    }

    public AgentResponse plan(AgentRequest request) {
        return plan(request, UUID.randomUUID().toString());
    }

    @Transactional
    public AgentResponse approve(UUID runId) {
        AgentRun run = runs.findLockedByIdAndTenantId(runId, tenantContext.tenantId())
                .orElseThrow(() -> new AgentRunNotFoundException(runId));
        if (run.getOutcome().equals("EXECUTED")) return response(run, true);
        if (!run.getOutcome().equals("PENDING_APPROVAL")) {
            throw new AgentApprovalException("Only pending plans can be approved");
        }
        List<Long> ids = createWorkItems(run.getGoal(), run.getClassification(), Priority.CRITICAL);
        run.approve(tenantContext.userId(), ids);
        return response(run, false);
    }

    private List<Long> createWorkItems(String goal, String classification, Priority priority) {
        List<Long> ids = new ArrayList<>(REQUIRED_TOOL_CALLS);
        List.of("Discover requirements for ", "Implement ", "Verify and document ")
                .forEach(prefix -> ids.add(workItems.save(new WorkItem(
                        prefix + goal, "Generated by the planning agent (" + classification + ")",
                        priority, WorkStatus.BACKLOG, tenantContext.tenantId())).getId()));
        return List.copyOf(ids);
    }

    private AgentResponse response(AgentRun run, boolean replayed) {
        List<String> trace = List.of(
                "Observe: accepted and normalized the goal",
                "Reason: classified the goal as " + run.getClassification(),
                "Policy: outcome is " + run.getOutcome(),
                "Budget: " + run.getToolBudget() + " of 3 tool calls authorized",
                replayed ? "Act: returned the existing idempotent result"
                        : actionDescription(run.getOutcome()));
        return new AgentResponse(run.getId(), run.getGoal(), run.getClassification(), run.getOutcome(),
                run.getOutcome().equals("PENDING_APPROVAL"), run.getIdempotencyKey(), run.getToolBudget(),
                trace, run.workItemIdList());
    }

    private String actionDescription(String outcome) {
        return switch (outcome) {
            case "EXECUTED" -> "Act: persisted a bounded three-step plan";
            case "PENDING_APPROVAL" -> "Act: paused before side effects for administrator approval";
            case "BLOCKED" -> "Act: rejected unsafe instructions without side effects";
            case "BUDGET_EXCEEDED" -> "Act: stopped because the plan exceeded its tool budget";
            default -> "Act: dry run completed without state changes";
        };
    }

    private String normalizeKey(String key) {
        String value = key == null || key.isBlank() ? UUID.randomUUID().toString() : key.trim();
        if (!value.matches("[A-Za-z0-9._:-]{8,80}")) {
            throw new InvalidIdempotencyKeyException();
        }
        return value;
    }

    private Priority priority(String goal) {
        return goal.matches(".*(urgent|production|security|outage).*") ? Priority.CRITICAL : Priority.MEDIUM;
    }

    private String correlationId() {
        String value = MDC.get("correlationId");
        return value == null ? "system" : value;
    }
}
