package com.fromzerotohero.mission.agent;

import com.fromzerotohero.mission.workitem.Priority;
import com.fromzerotohero.mission.workitem.WorkItem;
import com.fromzerotohero.mission.workitem.WorkItemRepository;
import com.fromzerotohero.mission.workitem.WorkStatus;
import com.fromzerotohero.mission.security.TenantContext;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.slf4j.MDC;

@Service
public class PlanningAgent {
    private final WorkItemRepository repository;
    private final AgentRunRepository runRepository;
    private final TenantContext tenantContext;

    public PlanningAgent(WorkItemRepository repository, AgentRunRepository runRepository,
            TenantContext tenantContext) {
        this.repository = repository;
        this.runRepository = runRepository;
        this.tenantContext = tenantContext;
    }

    @Transactional
    public AgentResponse run(AgentRequest request) {
        String goal = request.goal().trim();
        String normalized = goal.toLowerCase(Locale.ROOT);
        String classification = classify(normalized);
        Priority priority = normalized.matches(".*(urgent|production|security|outage).*" )
                ? Priority.CRITICAL : Priority.MEDIUM;

        List<String> trace = List.of(
                "Observe: accepted and normalized the goal",
                "Reason: classified the goal as " + classification,
                "Plan: decompose into discover, implement, and verify steps",
                request.createWorkItems() ? "Act: persisted the plan through the work-item tool"
                        : "Act: dry run requested; no state changed");

        List<Long> ids = new ArrayList<>();
        if (request.createWorkItems()) {
            List.of("Discover requirements for ", "Implement ", "Verify and document ")
                    .forEach(prefix -> ids.add(repository.save(new WorkItem(
                            prefix + goal, "Generated by the planning agent (" + classification + ")",
                            priority, WorkStatus.BACKLOG, tenantContext.tenantId())).getId()));
        }
        String correlationId = MDC.get("correlationId");
        AgentRun run = runRepository.save(new AgentRun(tenantContext.tenantId(), tenantContext.userId(),
                correlationId == null ? "system" : correlationId, goal, classification,
                request.createWorkItems() ? "EXECUTED" : "DRY_RUN", ids.size()));
        return new AgentResponse(run.getId(), goal, classification, trace, ids);
    }

    private String classify(String goal) {
        if (goal.matches(".*(test|quality|bug|playwright).*")) return "QUALITY_ENGINEERING";
        if (goal.matches(".*(deploy|aws|cloud|jenkins|release).*")) return "DELIVERY_AUTOMATION";
        if (goal.matches(".*(api|spring|backend|rest).*")) return "SOFTWARE_DEVELOPMENT";
        return "INTELLIGENT_AUTOMATION";
    }
}
