create table work_item (
    id bigint generated by default as identity primary key,
    title varchar(120) not null,
    description varchar(1000),
    priority varchar(20) not null,
    status varchar(30) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    version bigint not null default 0,
    constraint ck_work_item_priority check (priority in ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    constraint ck_work_item_status check (status in ('BACKLOG', 'READY', 'IN_PROGRESS', 'DONE'))
);

create index ix_work_item_updated_at on work_item (updated_at desc);
